# Generated by Django 6.0.5 on 2026-06-05 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_id', models.CharField(max_length=20, unique=True, verbose_name='ID/Carnet Estudiante')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('carrera', models.CharField(default='Informática', max_length=100, verbose_name='Carrera')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='ProgramaBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del programa')),
                ('tipo', models.CharField(choices=[('DOCENCIA', 'Auxiliar Docencia'), ('INVESTIGACION', 'Auxiliar Investigación'), ('COMEDOR1', 'Beca Comedor Cat.1'), ('COMEDOR2', 'Beca Comedor Cat.2'), ('TRANSPORTE', 'Beca Transporte'), ('DEPORTIVA', 'Beca Deportiva')], default='COMEDOR1', max_length=20, verbose_name='Tipo de beca')),
                ('monto', models.CharField(max_length=100, verbose_name='Monto/Beneficio')),
                ('requisito', models.TextField(verbose_name='Requisitos')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Programa activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Programa de Beca',
                'verbose_name_plural': 'Programas de Becas',
                'db_table': 'programas_beca',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_postulacion', models.DateField(auto_now_add=True, verbose_name='Fecha de postulación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='BecasUniv.estudiante')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='BecasUniv.programabeca')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'postulaciones',
                'ordering': ['-fecha_postulacion'],
            },
        ),
    ]
