# Generated by Django 6.0.5 on 2026-06-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BecasUniv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='estudiante_id',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ci',
            field=models.CharField(default=0, max_length=15, unique=True, verbose_name='Carnet de Identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='registro_universitario',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Registro Universitario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', '⏳ Pendiente'), ('APROBADA', '✅ Aprobada'), ('RECHAZADA', '❌ Rechazada')], default='PENDIENTE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='programabeca',
            name='tipo',
            field=models.CharField(choices=[('DOCENCIA', '🎓 Auxiliar Docencia'), ('INVESTIGACION', '🔬 Auxiliar Investigación'), ('COMEDOR1', '🍽️ Beca Comedor Cat.1'), ('COMEDOR2', '🍽️ Beca Comedor Cat.2'), ('TRANSPORTE', '🚌 Beca Transporte'), ('DEPORTIVA', '⚽ Beca Deportiva')], default='COMEDOR1', max_length=20, verbose_name='Tipo de beca'),
        ),
    ]
